/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Services.Interfaces.Interfaces;
import Services.MyClient;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javalibrary.model.reponse.ListRelatedTopicReponse;
import javalibrary.model.reponse.RelatedTopicReponse;
import javalibrary.model.request.RelatedTopicRequest;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author trann
 */
public class RelatedTopicPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchOverTimePanel
     */
    JLabel loading;
    public RelatedTopicPanel() {
        initComponents();
        initUI();
    }
    public void loadData(RelatedTopicRequest relatedTopicRequest){
        showLoading();
        MyClient.getInstance().getRelatedTopic(relatedTopicRequest,new Interfaces.IRelatedTopicListener() {
            @Override
            public void OnGetRelatedTopicSuccess(List<RelatedTopicReponse> listRelatedTopicReponse) {
                initData(listRelatedTopicReponse);
                dismisLoading(); }

            @Override
            public void OnGetRelatedTopicFailed() {
            dismisLoading();
                showTryAgain();
          }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(153, 255, 51));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void initData(List<RelatedTopicReponse> list) {
        for(int i =0 ;i<list.size();i++){
            add(new TopicItemView(list.get(i)));
        }
        invalidate();

  }

    private void showLoading() {
        jScrollPane1.setVisible(false);
         loading.setVisible(true);
         invalidate();
    }
     
    private void dismisLoading(){
        jScrollPane1.setVisible(true);
         loading.setVisible(false);
         invalidate();
    
    }
    private void showTryAgain(){
    
    }
    private void onTryAgainClick(){
    
    }

    private void initUI() {
        Icon loadingImage = new ImageIcon(this.getClass().getResource("../image/goodLoading.gif"));
        loading = new JLabel(loadingImage);
        loading.setVisible(false);
        loading.setSize(200, 200);
        loading.setLocation(600, 200);
        add(loading,BorderLayout.CENTER);
    }
}
