name: Build & Deploy
on:
  push:
    branches: [develop]
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Deploy NodeJS app"
        uses: appleboy/ssh-action@v0.1.2
        with: 
          host: "${{secrets.SSH_HOST}}"
          key: "${{secrets.SSH_KEY}}"
          script: cd /&&cd root&&cd JavaSocket&&git pull origin develop&&cd servers&&pm2 reload javasocket.sh --name=javasocket&&pm2 reload servers/pytrend-server/main.py&&echo "deploy success"
          username: "${{ secrets.SSH_USERNAME }}"
